---
- name: Copy anti-ddos script
  ansible.builtin.copy:
    src: files/ipv4-rules.sh
    dest: /tmp/ipv4-rules.sh
    mode: '0500'

- name: run anti-ddos script
  become: yes
  shell: /tmp/ipv4-rules.sh start
